# Settings about the model
model: roberta-base
hidden_size: 768
mlm_head_intermediate_size: 200
num_classes: 2
max_len: 512
dropout: 0.2
head_hidden_size: 400

# Num classes for the two datasets
n_class_pavlopoulos20: 2
n_class_yu22: 3

# Device settings
device: cuda:0

# Seed
seed: [42,55,78,251,363,488, 566, 723, 122, 1896]

# Training settings
batch_size: 8
training_epochs: 20
cv_splits: 5


# Optimizer settings
optimizer: Adam
#lr: 0.000003
lr: 0.00002
#lr: 0.001 #0.001
weight_decay: 0.0001 #0.0001

# Criterion
criterion: CrossEntropyLoss

# Path for saved models
model_save_path: weights

# Path of result file
results_path: results/results.csv