# Settings about the model
model: roberta-base
# Num classes for the two datasets
n_class_pavlopoulos20: 2
n_class_yu22: 3
class_names_pavlopoulos20: ["not-hate","hate"]
class_names_yu22: ["hate","neutral","counter-hate"]

# Device settings
device: cuda:0

# Training settings
batch_size: 16
training_epochs: 20

# Optimizer settings
optimizer: Adam
lr: 0.00001
weight_decay: 0.0001

# Criterion
criterion: CrossEntropyLoss

# Path for saved models
model_save_path: weights

# Path of result file
results_path: results/results.csv
explainability_results_path: results/explainability_results.csv