# Settings about the model
model: roberta-base
# Num classes for the two datasets
n_class_pavlopoulos20: 2
n_class_yu22: 3

# Device settings
device: cuda:0

# Training settings
batch_size: 16
training_epochs: 20


# Optimizer settings
optimizer: AdamW
#lr: 0.000003
#lr: 0.000001
lr: 0.00001
#lr: 0.001 #0.001
weight_decay: 0.0001 #0.0001

# Criterion
criterion: CrossEntropyLoss

# Path for saved models
model_save_path: weights

# Path of result file
results_path: results/results.csv